<?php
function _update_prizes_callback($form, $form_state)
{
    return $form['field_prizes'];
}

function _update_event_location_callback($form, $form_state)
{
    return $form['field_event_location'];
}

function govhack_project_form_alter(&$form, &$form_state, $form_id)
{
    if ($form_id == 'project_node_form') {
        $form['field_event_location']['und']['#ajax'] = array(
            'callback' => '_update_prizes_callback',
            'wrapper' => 'prizes_wrapper',
        );
        $form['field_prizes']['und']['#prefix'] = '<div id="prizes_wrapper">';
        $form['field_prizes']['und']['#suffix'] = '</div>';

        $form['field_region']['und']['#ajax'] = array(
            'callback' => '_update_event_location_callback',
            'wrapper' => 'event_location_wrapper',
        );
        $form['field_event_location']['und']['#prefix'] = '<div id="event_location_wrapper">';
        $form['field_event_location']['und']['#suffix'] = '</div>';

        $form['field_ready']['und']['#prefix'] = '<div id="ready_wrapper" style="display:none;">';
        $form['field_ready']['und']['#suffix'] = '</div>';

        if ($form_state['node']->field_ready['und'][0]['value'] == 1) {
            $form['#prefix'] = "<div class=\"messages status bg-success img-rounded\"><p style=\"padding: 16px;\">This project has been submitted but you can still <a href='#' id=unlock>Re-Open Project</a> now to make further changes</p></div><br/>";
        }
        $form['#suffix'] = '<script>
var veryReady;
function checkReadiness() {
  ready = true;
  // ready if source code and (video link provided or video upload widget removed jQuery(".s3fs-cors-upload-file")) 
  if (!jQuery( "#edit-field-download-url-und-0-url" ).val()) {
    ready = false;
  }
  if (!jQuery( "#edit-field-video-url-und-0-url" ).val() && !jQuery(".s3fs-cors-upload-file")) {
    ready = false;
  }
  
  
  if (ready && !veryReady) {
             jQuery("#edit-actions").append(\'<input type="submit" id="edit-submit-project" name="op" value="Submit your entry" class="form-submit btn btn-info pull-right">\');
                      jQuery("#edit-submit-project").click(function() {
           jQuery("#edit-field-ready-und").prop(\'checked\', true);
           jQuery("#edit-submit").click();
         })
             veryReady = true;
  }
}
       jQuery(function() {
         jQuery("#unlock").click(function() {
                       jQuery("#project-node-form").css("opacity", 1.0);
                       jQuery("#edit-field-ready-und").prop("checked", false);
            jQuery("#project-node-form :input").prop("disabled", false);
         });

         
         if (jQuery("#edit-field-ready-und").prop("checked")) {
            jQuery("#project-node-form").css("opacity", 0.5);
            jQuery("#project-node-form :input").prop("disabled", true);
        }
        checkReadiness();
        jQuery( "#edit-field-download-url-und-0-url, #edit-field-video-url-und-0-url" ).change(function() {
          checkReadiness();
        });
        });
</script>';


        $form['field_official_datasets_values']['und']['#suffix'] = '
        <script>
        var thisField;
        if (!String.prototype.includes) {
  String.prototype.includes = function(search, start) {
    \'use strict\';
    if (typeof start !== \'number\') {
      start = 0;
    }
    
    if (start + search.length > this.length) {
      return false;
    } else {
      return this.indexOf(search, start) !== -1;
    }
  };
}
function attachCKANAutocomplete() {
  jQuery("#edit-field-official-datasets .link-field-url input").each(function() {
        jQuery(this).change(function() {
            if (jQuery(this).val().includes("/dataset/")) {
                thisField = jQuery(this);
                jQuery.getJSON(jQuery(this).val().replace("/dataset/", "/api/3/action/package_show?id="), function(data) {
                    thisField.closest("tr").find(".field-name-field-dataset-name input").val(data.result.title);
                    thisField.closest("tr").find(".field-name-field-publishing-organisation input").val(data.result.organization.title);
                    if (data.result.jurisdiction === "Commonwealth of Australia") {
                        thisField.closest("tr").find(".field-name-field-jurisdiction-of-data select").val("Australian Government");
                    } else {
                      thisField.closest("tr").find(".field-name-field-jurisdiction-of-data select").val(data.result.jurisdiction);
                    }
                });
            };
        });
    });
}
        jQuery(function() {
    attachCKANAutocomplete() ;
});

Drupal.behaviors.MyModule = {
    attach: function (context, settings) { 
          //Called after ajax event returns data
              Drupal.ajax["edit-field-official-datasets-und-add-more"].success = function(response, status) {
                setTimeout(function() {
      attachCKANAutocomplete();
    }, 100)
                 //Pass back to original method
                 Drupal.ajax.prototype.success.call(this, response, status);
             }
            
            }
            }
        </script>';


    }
}

/**
 * Implements hook_block_info().
 * http://kahthong.com/2013/06/create-your-own-custom-drupal-block-programmatically
 */
function govhack_project_block_info()
{
    $blocks = array();
    $blocks['scorecard'] = array(
        'info' => t('GovHack Score card'),
    );
    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function govhack_project_block_view($delta = '')
{
    $block = array();
    switch ($delta) {
        case 'scorecard':
            $block['subject'] = '';
            $block['content'] = _govhack_project_scorecard_content();
            break;
    }
    return $block;
}

function _govhack_project_scorecard_content()
{
    $output = t('Hello world');
    return $output;
}